pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

steps:

- task: SonarCloudPrepare@1
  displayName: Prep SonarCloud
  inputs:
    SonarCloud: 'Customisation'
    organization: 'cloud-awesome'
    scannerMode: 'MSBuild'
    projectKey: 'cds-customisation'
    projectName: 'cds-customisation'

- task: NuGetCommand@2
  displayName: Restore NuGet
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '**\*.sln'
    configuration: 'release'

- task: CopyFiles@2
  displayName: TEMP - Copy manifests to relative path
  inputs:
    SourceFolder: 'src/CloudAwesome.Xrm.Customisation/CloudAwesome.Xrm.Customisation.Tests/TestManifests'
    Contents: '**'
    TargetFolder: 'D:/a/TestManifests'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: TEMP - Copy sample assembly to relative path
  inputs:
    SourceFolder: 'src/CloudAwesome.Xrm.Customisation/SamplePluginAssembly/bin/release/SamplePluginAssembly.dll'
    Contents: '**'
    TargetFolder: 'D:/SamplePluginAssembly/bin/release'
    CleanTargetFolder: true
    OverWrite: true
    
- task: VSTest@2
  displayName: Execute Unit Tests
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'src\CloudAwesome.Xrm.Customisation\CloudAwesome.Xrm.Customisation.Tests\bin\Release\CloudAwesome.Xrm.Customisation.Tests.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'Category!=IgnoreInPipeline'
    codeCoverageEnabled: true
    testRunTitle: '$(Build.BuildNumber)'

- task: SonarCloudAnalyze@1
  displayName: SonarCloud Analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud Results
  inputs:
    pollingTimeoutSec: '300'