pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*

steps:

- task: SonarCloudPrepare@1
  displayName: Prep SonarCloud
  inputs:
    SonarCloud: 'Customisation'
    organization: 'cloud-awesome'
    scannerMode: 'MSBuild'
    projectKey: 'cds-customisation'
    projectName: 'cds-customisation'

- task: NuGetCommand@2
  displayName: Restore NuGet
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '**\*.sln'
    configuration: 'release'

- task: VSTest@2
  displayName: Execute Unit Tests
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    testRunTitle: '$(Build.BuildNumber)'

- task: SonarCloudAnalyze@1
  displayName: SonarCloud Analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud Results
  inputs:
    pollingTimeoutSec: '300'