name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

pool:
  vmImage: 'windows-latest'

trigger:
  tags:
    include:
    - v*

steps:

- task: NuGetCommand@2
  displayName: Restore NuGet
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '**\*.sln'
    configuration: 'release'

- task: CopyFiles@2
  displayName: TEMP - Copy manifests to relative path
  inputs:
    SourceFolder: 'src/CloudAwesome.Xrm.Customisation/CloudAwesome.Xrm.Customisation.Tests/TestManifests'
    Contents: '**'
    TargetFolder: 'D:/a/TestManifests'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: TEMP - Copy sample assembly to relative path
  inputs:
    SourceFolder: 'src/CloudAwesome.Xrm.Customisation/SamplePluginAssembly/bin/release/SamplePluginAssembly.dll'
    Contents: '**'
    TargetFolder: 'D:/SamplePluginAssembly/bin/release'
    CleanTargetFolder: true
    OverWrite: true

- task: VSTest@2
  displayName: Execute Unit Tests
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'src\CloudAwesome.Xrm.Customisation\CloudAwesome.Xrm.Customisation.Tests\bin\Release\CloudAwesome.Xrm.Customisation.Tests.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'Category!=IgnoreInPipeline'
    codeCoverageEnabled: true
    testRunTitle: '$(Build.BuildNumber)'

- task: NuGetCommand@2
  displayName: Nuget Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/CloudAwesome.Xrm.Customisation.csproj'
    configuration: 'release'
    versioningScheme: 'byBuildNumber'

- task: GitHubRelease@1
  displayName: Create GitHub Release with ChangeLog
  inputs:
    gitHubConnection: 'GitHubReleaseConnection'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    #assets: $(Build.ArtifactStagingDirectory)/*
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
    changeLogLabels: '[{ "label" : "enhancement", "displayName" : "New features", "state" : "closed" }, { "label" : "bug", "displayName" : "Bugs fixed", "state" : "closed" }, { "label" : "documentation", "displayName" : "Documentation added", "state" : "closed" }]'
    
- task: NuGetCommand@2
  displayName: Nuget Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'cds.customisation'