//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\Oculu\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://awesome-sandbox.api.crm11.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CloudAwesome.Xrm.Customisation" /out:"C:\Source\Cloud-Awesome\cds-customisation\src\CloudAwesome.Xrm.Customisation\CloudAwesome.Xrm.Customisation\EarlyBoundModels\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"arthur@cloudawesome.uk" /password:"************************************" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace CloudAwesome.Xrm.Customisation
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppElement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppElement> AppElementSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppElement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModule> AppModuleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModuleComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModuleComponent> AppModuleComponentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModuleComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModuleComponentEdge"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModuleComponentEdge> AppModuleComponentEdgeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModuleComponentEdge>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModuleComponentNode"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModuleComponentNode> AppModuleComponentNodeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModuleComponentNode>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModuleMetadata"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModuleMetadata> AppModuleMetadataSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModuleMetadata>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppModuleRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppModuleRoles> AppModuleRolesSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppModuleRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.AppSetting"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.AppSetting> AppSettingSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.AppSetting>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.PluginAssembly"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.PluginAssembly> PluginAssemblySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.PluginAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.PluginType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.PluginType> PluginTypeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.PluginType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.Role> RoleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessage> SdkMessageSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageFilter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageFilter> SdkMessageFilterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageFilter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessagePair"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessagePair> SdkMessagePairSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessagePair>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageProcessingStep"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepImage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepImage> SdkMessageProcessingStepImageSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepImage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepSecureConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepSecureConfig> SdkMessageProcessingStepSecureConfigSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageProcessingStepSecureConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageRequest"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageRequest> SdkMessageRequestSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageRequest>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageRequestField"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageRequestField> SdkMessageRequestFieldSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageRequestField>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageResponse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageResponse> SdkMessageResponseSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageResponse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SdkMessageResponseField"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SdkMessageResponseField> SdkMessageResponseFieldSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SdkMessageResponseField>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.ServiceEndpoint"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.ServiceEndpoint> ServiceEndpointSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.ServiceEndpoint>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.SiteMap"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.SiteMap> SiteMapSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.SiteMap>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}