//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\ArthurNicholson-Gumu\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\CrmSvcUtil.exe" /url:"https://altusukes-d365-dev2.api.crm11.dynamics.com" /namespace:"CloudAwesome.Xrm.Customisation.EarlyBoundModels" /SuppressGeneratedCodeAttribute /out:"C:\Source\Cloud-Awesome\cds-customisation\src\CloudAwesome.Xrm.Customisation\CloudAwesome.Xrm.Customisation\EarlyBoundModels\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"Arthur.Nicholson-Gumua@altusgroup.com" /password:"************************************" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]

namespace CloudAwesome.Xrm.Customisation.EarlyBoundModels
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppElement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppElement> AppElementSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppElement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModule> AppModuleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponent> AppModuleComponentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentEdge"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentEdge> AppModuleComponentEdgeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentEdge>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentNode"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentNode> AppModuleComponentNodeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleComponentNode>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleMetadata"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleMetadata> AppModuleMetadataSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleMetadata>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleRoles> AppModuleRolesSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppModuleRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppSetting"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppSetting> AppSettingSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.AppSetting>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPI"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPI> CustomAPISet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPI>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIRequestParameter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIRequestParameter> CustomAPIRequestParameterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIRequestParameter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIResponseProperty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIResponseProperty> CustomAPIResponsePropertySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.CustomAPIResponseProperty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginAssembly"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginAssembly> PluginAssemblySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginType> PluginTypeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.PluginType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.Publisher"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Publisher> PublisherSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Publisher>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.Role"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Role> RoleSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Role>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessage> SdkMessageSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageFilter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageFilter> SdkMessageFilterSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageFilter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessagePair"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessagePair> SdkMessagePairSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessagePair>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStep"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepImage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepImage> SdkMessageProcessingStepImageSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepImage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepSecureConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepSecureConfig> SdkMessageProcessingStepSecureConfigSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageProcessingStepSecureConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequest"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequest> SdkMessageRequestSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequest>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequestField"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequestField> SdkMessageRequestFieldSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageRequestField>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponse> SdkMessageResponseSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponseField"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponseField> SdkMessageResponseFieldSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SdkMessageResponseField>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.ServiceEndpoint"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.ServiceEndpoint> ServiceEndpointSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.ServiceEndpoint>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.SiteMap"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SiteMap> SiteMapSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.SiteMap>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CloudAwesome.Xrm.Customisation.EarlyBoundModels.Workflow"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Workflow> WorkflowSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<CloudAwesome.Xrm.Customisation.EarlyBoundModels.Workflow>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}